config/routes.rb
Rails.application.routes.draw do
  root 'quizs#index'
  resources :quizs
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quizs_controller.rb
class QuizsController < ApplicationController

  def index
    @quizs = Quiz.all
  end

  def new
    @quiz = Quiz.new
  end

  def create
    Quiz.create(quiz_params)
    redirect_to root_path
  end

  private

  def quiz_params
    params.require(:quizzes).permit(:make, :model, :seats)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizs_helper.rb
module QuizsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizs/index.html.erb
<h1> Welcome to my Quiz2 page.</h1>
<h2> <%= @quizs.inspect %></h2>
<h3> <%= link_to "Submit a new car", new_quiz_url %>

app/views/quizs/new.html.erb
<h1>Tell me about this new car</h1>
  <%= simple_form_for :quiz, url: :quizs do |f| %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :seats %>
    <br/>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>